AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'config/initializers/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
